---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: demoapplication
  name: demoapplication
  namespace: test
spec:
  tls:
  - hosts:
    - demoapp.tools.aws.cps.vodafone.com
    secretName: tools-multisite-cert-secret
  rules:
  - host: demoapp.tools.aws.cps.vodafone.com
    http:
      paths:
      - backend:
          serviceName: demoapplication
          servicePort: 9900
        path: /
